/*
 * This file was generated by the Gradle "init" task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 */
plugins {
    "kotlin-dsl"
}

ext {
	 set("DEBUG", true)
}

buildscript {
    repositories {
        maven("https://maven.aliyun.com/repository/public/") 
        maven("https://maven.aliyun.com/repository/google/") 
        maven("https://maven.aliyun.com/repository/gradle-plugin/") 
        maven("https://clojars.org/repo/") 
        maven("https://jitpack.io") 
        google()
        mavenLocal()
        mavenCentral()
    }
    
}

allprojects {
    apply(plugin = "eclipse")
    repositories {
        maven("https://maven.aliyun.com/repository/public/") 
        maven("https://maven.aliyun.com/repository/google/") 
        maven("https://maven.aliyun.com/repository/gradle-plugin/") 
        maven("https://clojars.org/repo/") 
        maven("https://jitpack.io") 
        google()
        mavenLocal()
        mavenCentral()
    }
}

task("clean", Delete::class) {
	delete("${rootDir}/outputs")
}

